apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: octopetshop-production
spec:
  generators:
  - list:
       elements:
       - cluster: in-cluster
         url: https://kubernetes.default.svc 
  template:
    metadata:
      name: '{{cluster}}-octopetshop-production'
      annotations:
        codefresh.io/product: octopetshop

    spec:
      project: default
      source:
        repoURL: https://github.com/robpearson/cf-octopetshop.git
        targetRevision: HEAD
        path: k8s/kustomize/rollout/overlays/Production
      destination:
        server: '{{url}}'
        namespace: production
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        - Validate=false
        - CreateNamespace=true