apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base

patches:
  - target:
      kind: Deployment
      name: octopetshop-web-deployment
    path: octopetshop-web-deployment.yaml
  - target: 
      kind: Ingress
      name: octopetshop-ingress
    path: octopetshop-ingress.yaml
  - target:
      kind: Service
      name: octopetshop-web-cluster-ip-service
    path: octopetshop-web-cluster-ip-service.yaml

# images:
# - name: octopussamples/octopetshop-database
#   newName: robpearson/cf-octopetshop-database
#   newTag: 2024.194.23.3836
# - name: octopussamples/octopetshop-productservice
#   newName: robpearson/cf-octopetshop-productservice
#   newTag: 2024.194.23.3836
# - name: octopussamples/octopetshop-shoppingcartservice
#   newName: robpearson/cf-octopetshop-shoppingcartservice
#   newTag: 2024.194.23.3836
# - name: octopussamples/octopetshop-web
#   newName: robpearson/cf-octopetshop-web
#   newTag: 2024.194.23.3836
